# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="subtitle_srt",
            field=models.FileField(blank=True, null=True, upload_to="dubbed_videos/"),
        ),
    ]
