# Generated by Codex on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_subtitle_srt"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="share_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
