# Generated by Codex on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_share_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]

