# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_progress_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="feedback_rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="feedback_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="feedback_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

