# Generated by Codex on 2026-03-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_feedback(apps, schema_editor):
    Video = apps.get_model("videos", "Video")
    VideoFeedback = apps.get_model("videos", "VideoFeedback")

    for video in Video.objects.all().iterator():
        rating = getattr(video, "feedback_rating", None)
        text = (getattr(video, "feedback_text", "") or "").strip()
        updated_at = getattr(video, "feedback_updated_at", None)

        if rating is None and not text:
            continue

        safe_rating = int(rating) if rating is not None else 3
        feedback, created = VideoFeedback.objects.get_or_create(
            video_id=video.id,
            user_id=video.user_id,
            defaults={"rating": safe_rating, "comment": text},
        )
        if not created:
            feedback.rating = safe_rating
            feedback.comment = text
            feedback.save(update_fields=["rating", "comment"])

        if updated_at:
            VideoFeedback.objects.filter(id=feedback.id).update(updated_at=updated_at)


def backwards_copy_feedback(apps, schema_editor):
    Video = apps.get_model("videos", "Video")
    VideoFeedback = apps.get_model("videos", "VideoFeedback")

    for video in Video.objects.all().iterator():
        feedback = (
            VideoFeedback.objects.filter(video_id=video.id, user_id=video.user_id)
            .order_by("-updated_at")
            .first()
        )
        if not feedback:
            continue
        video.feedback_rating = feedback.rating
        video.feedback_text = feedback.comment
        video.feedback_updated_at = feedback.updated_at
        video.save(update_fields=["feedback_rating", "feedback_text", "feedback_updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_feedback_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="video_feedbacks", to=settings.AUTH_USER_MODEL)),
                ("video", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="videos.video")),
            ],
        ),
        migrations.AddConstraint(
            model_name="videofeedback",
            constraint=models.UniqueConstraint(fields=("video", "user"), name="uniq_video_feedback_per_user"),
        ),
        migrations.RunPython(forwards_copy_feedback, backwards_copy_feedback),
        migrations.RemoveField(
            model_name="video",
            name="feedback_rating",
        ),
        migrations.RemoveField(
            model_name="video",
            name="feedback_text",
        ),
        migrations.RemoveField(
            model_name="video",
            name="feedback_updated_at",
        ),
    ]

