# Generated by Codex on 2026-03-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_feedback_fields"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="BillingTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("txn_type", models.CharField(choices=[("top_up", "Top Up"), ("dubbing_charge", "Dubbing Charge"), ("refund", "Refund")], max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="billing_transactions", to=settings.AUTH_USER_MODEL)),
                ("video", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_transactions", to="videos.video")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

