"""
Django settings for dubbing_site project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from celery.schedules import crontab
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(file_path):
    if not file_path.exists():
        return

    for raw_line in file_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def env(name, default=None):
    return os.environ.get(name, default)


def env_bool(name, default=False):
    value = env(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = env(name)
    if value is None or value == "":
        return default
    return int(value)


def env_list(name, default=None):
    value = env(name)
    if value is None or value.strip() == "":
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", "django-insecure-change-me-in-env")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", [])
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'corsheaders',
    'users',
    'videos',
    'dubbing',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dubbing_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dubbing_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / env("DJANGO_DB_NAME", "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]   
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", True)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", [])

# Production HTTPS/security (typically behind Nginx or cloud LB)
USE_X_FORWARDED_PROTO = env_bool("USE_X_FORWARDED_PROTO", True)
if USE_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_REFERRER_POLICY = env("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_BROWSER_XSS_FILTER = env_bool("SECURE_BROWSER_XSS_FILTER", True)

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Celery
CELERY_BROKER_URL = env("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = env_int("CELERY_WORKER_PREFETCH_MULTIPLIER", 1)
CELERY_WORKER_MAX_TASKS_PER_CHILD = env_int("CELERY_WORKER_MAX_TASKS_PER_CHILD", 0)
CELERY_TASK_REJECT_ON_WORKER_LOST = env_bool("CELERY_TASK_REJECT_ON_WORKER_LOST", False)

CELERY_DUBBING_GPU_QUEUE = env("CELERY_DUBBING_GPU_QUEUE", "dubbing_gpu")
CELERY_DUBBING_CPU_QUEUE = env("CELERY_DUBBING_CPU_QUEUE", "dubbing_cpu")
CELERY_DEFAULT_QUEUE = CELERY_DUBBING_CPU_QUEUE
CELERY_GPU_AUTOSCALE_MIN = env_int("CELERY_GPU_AUTOSCALE_MIN", 1)
CELERY_GPU_AUTOSCALE_MAX = env_int("CELERY_GPU_AUTOSCALE_MAX", 3)
CELERY_CPU_AUTOSCALE_MIN = env_int("CELERY_CPU_AUTOSCALE_MIN", 1)
CELERY_CPU_AUTOSCALE_MAX = env_int("CELERY_CPU_AUTOSCALE_MAX", 6)
CELERY_GPU_POOL = env("CELERY_GPU_POOL", "prefork")
CELERY_CPU_POOL = env("CELERY_CPU_POOL", "prefork")
CELERY_TASK_QUEUES = (
    Queue(CELERY_DUBBING_CPU_QUEUE),
    Queue(CELERY_DUBBING_GPU_QUEUE),
)
CELERY_TASK_ROUTES = {
    "dubbing.tasks.process_video_dubbing": {"queue": CELERY_DUBBING_GPU_QUEUE},
    "videos.tasks.delete_expired_videos": {"queue": CELERY_DUBBING_CPU_QUEUE},
}

VIDEO_RETENTION_DAYS = env_int("VIDEO_RETENTION_DAYS", 7)
DUBBING_STALE_JOB_TIMEOUT_MINUTES = env_int("DUBBING_STALE_JOB_TIMEOUT_MINUTES", 180)
DUBBING_MAX_ACTIVE_PER_USER = env_int("DUBBING_MAX_ACTIVE_PER_USER", 1)
DUBBING_MAX_GLOBAL_ACTIVE = env_int("DUBBING_MAX_GLOBAL_ACTIVE", 20)
BILLING_ENABLED = env_bool("BILLING_ENABLED", True)
BILLING_CURRENCY = env("BILLING_CURRENCY", "KZT")
# KZT-based pricing (backward compatible with legacy env names).
BILLING_MIN_START_BALANCE = env(
    "BILLING_MIN_START_BALANCE_KZT",
    env("BILLING_MIN_START_BALANCE", "100.00"),
)
GPU_PRICE_PER_MINUTE = env(
    "GPU_PRICE_PER_MINUTE_KZT",
    env("GPU_PRICE_PER_MINUTE", "15.00"),
)
DUBBING_ESTIMATE_PRICE_PER_VIDEO_MINUTE = env(
    "DUBBING_ESTIMATE_PRICE_PER_VIDEO_MINUTE_KZT",
    env("DUBBING_ESTIMATE_PRICE_PER_VIDEO_MINUTE", "2000.00"),
)
STORAGE_PRICE_PER_GB = env(
    "STORAGE_PRICE_PER_GB_KZT",
    env("STORAGE_PRICE_PER_GB", "0.50"),
)

# Dubbing pipeline
FFMPEG_BIN = env("FFMPEG_BIN", "ffmpeg")
GROQ_API_KEY = env("GROQ_API_KEY", "")
DUBBING_SOURCE_LANGUAGE_NAME = env("DUBBING_SOURCE_LANGUAGE_NAME", "English")
DUBBING_TARGET_LANGUAGE_NAME = env("DUBBING_TARGET_LANGUAGE_NAME", "Kazakh")
GROQ_ASR_MODEL = env("GROQ_ASR_MODEL", "whisper-large-v3")
NLLB_MODEL_DIR = env(
    "NLLB_MODEL_DIR",
    r"C:\Users\AKBAR\.cache\huggingface\hub\models--facebook--nllb-200-distilled-600M",
)
NLLB_SOURCE_LANG = env("NLLB_SOURCE_LANG", "eng_Latn")
NLLB_TARGET_LANG = env("NLLB_TARGET_LANG", "kaz_Cyrl")
NLLB_BATCH_SIZE = env_int("NLLB_BATCH_SIZE", 8)
NLLB_MAX_NEW_TOKENS = env_int("NLLB_MAX_NEW_TOKENS", 256)
DIARIZATION_MODEL_NAME = env("DIARIZATION_MODEL_NAME", "pyannote/speaker-diarization-3.1")
DIARIZATION_MIN_SPEAKERS = env("DIARIZATION_MIN_SPEAKERS", "")
DIARIZATION_MAX_SPEAKERS = env("DIARIZATION_MAX_SPEAKERS", "")
HUGGINGFACE_TOKEN = env("HUGGINGFACE_TOKEN", "")
COQUI_XTTS_LOCAL_DIR = env("COQUI_XTTS_LOCAL_DIR", "")
XTTS_FALLBACK_LANGUAGE = env("XTTS_FALLBACK_LANGUAGE", "tr")
DUBBING_SOURCE_LANGUAGE = env("DUBBING_SOURCE_LANGUAGE", "")
TTS_TARGET_LANGUAGE = env("TTS_TARGET_LANGUAGE", "")
MIN_SEGMENT_DURATION_SECONDS = float(env("MIN_SEGMENT_DURATION_SECONDS", "0.6"))
MAX_SPEAKER_GAP_SECONDS = float(env("MAX_SPEAKER_GAP_SECONDS", "0.25"))
MIN_TEMPO_FACTOR = float(env("MIN_TEMPO_FACTOR", "0.85"))
MAX_TEMPO_FACTOR = float(env("MAX_TEMPO_FACTOR", "1.15"))
TRANSLATION_MAX_LENGTH_RATIO = float(env("TRANSLATION_MAX_LENGTH_RATIO", "1.25"))
SPEAKER_REF_TARGET_SECONDS = float(env("SPEAKER_REF_TARGET_SECONDS", "8.0"))
SPEAKER_REF_MIN_SECONDS = float(env("SPEAKER_REF_MIN_SECONDS", "6.0"))
SPEAKER_REF_MAX_SECONDS = float(env("SPEAKER_REF_MAX_SECONDS", "12.0"))
SPEAKER_REF_MIN_SEGMENT_SECONDS = float(env("SPEAKER_REF_MIN_SEGMENT_SECONDS", "1.5"))
MAX_UPLOAD_VIDEO_MB = env_int("MAX_UPLOAD_VIDEO_MB", 100)
ALLOWED_VIDEO_CONTENT_TYPES = env_list(
    "ALLOWED_VIDEO_CONTENT_TYPES",
    ["video/mp4", "video/quicktime", "video/x-matroska", "video/webm"],
)
VALIDATE_ORIGINAL_VIDEO_ENGLISH = env_bool("VALIDATE_ORIGINAL_VIDEO_ENGLISH", False)

CELERY_BEAT_SCHEDULE = {
    "delete-expired-videos-daily": {
        "task": "videos.tasks.delete_expired_videos",
        "schedule": crontab(hour=3, minute=0),
    },
    "fail-stale-dubbing-jobs": {
        "task": "videos.tasks.fail_stale_dubbing_jobs",
        "schedule": crontab(minute="*/10"),
    },
}
